### ISSUE TITLE
Non technical comment...

### ISSUE THREAD

**Issue by boydkelly** [jaredh159/asciidork#23]
Hi,

Very intresting project.   But with all due respect (seriously),  are you really wanting to keep this name?   Maybe that was intentional or tongue in cheek, but from one techie to another, could you consider a name change?

Dork:  Dork is a purely derogatory term and carries with it no implication of useful skills or knowledge. Socially inept; contemptible.

Is this really what you want to associate to your project as well as asciidoc ?

**Comment by jaredh159** [comment]
hi there. my thought is as follows:

- asciidoc is weirdly protective of their name, i can't use it in any way without getting a complaint from them
- the `r` in asciidork is a subtle reference to _Rust_
- i think of "dork" as meaning "nerdy", hence the emoji, it's slightly tongue-in-cheek, and doesn't take itself too seriously

i don't have any plans to change the name. i'm not saying i wouldn't ever do it, but i like it as it is now. :)
